version: '3'
services: 
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - influxdb-volume:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=banco_temporal
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on: 
      - influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - grafana-volume:/var/lib/grafana

volumes:
  telegraf-volume:
    driver: local
    driver_opts:
      type: none
      device: $PWD/volumes/telegraf
      o: bind
  grafana-volume:
    driver: local
    driver_opts:
      type: none
      device: $PWD/volumes/grafana
      o: bind
  influxdb-volume:
    driver: local
    driver_opts:
      type: none
      device: $PWD/volumes/influxdb
      o: bind